# Generated by Django 5.1.7 on 2025-05-15 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_event_is_archived"),
    ]

    operations = [
        migrations.DeleteModel(
            name="RSVP",
        ),
    ]
