# Generated by Django 5.2 on 2025-05-20 11:26

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_delete_rsvp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-event_date']},
        ),
        migrations.AlterModelOptions(
            name='eventcategory',
            options={'verbose_name_plural': 'Event Categories'},
        ),
        migrations.RemoveField(
            model_name='event',
            name='attendance_count',
        ),
        migrations.RemoveField(
            model_name='event',
            name='publish_date',
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='short_description',
            field=models.CharField(max_length=300),
        ),
    ]
