# Generated by Django 5.2 on 2025-05-22 09:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mlc_constituency', models.CharField(max_length=255, verbose_name='MLC CONSTITUENCY')),
                ('assembly', models.CharField(max_length=255, verbose_name='ASSEMBLY')),
                ('mandal', models.CharField(max_length=255, verbose_name='MANDAL')),
                ('sno', models.CharField(max_length=50, verbose_name='SNO')),
                ('mobile_no', models.CharField(max_length=15, verbose_name='MOBILE NO')),
                ('town', models.CharField(blank=True, max_length=255, null=True, verbose_name='TOWN')),
                ('village', models.CharField(blank=True, max_length=255, null=True, verbose_name='VILLAGE')),
                ('psno', models.CharField(blank=True, max_length=50, null=True, verbose_name='PSNO')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='LOCATION')),
                ('ps_address', models.TextField(blank=True, null=True, verbose_name='PS ADDRESS')),
                ('street', models.CharField(blank=True, max_length=255, null=True, verbose_name='STREET')),
                ('hno', models.CharField(blank=True, max_length=50, null=True, verbose_name='HNO')),
                ('card_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='CARD NO')),
                ('voter_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='VOTER NAME')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='AGE')),
                ('gender', models.CharField(blank=True, max_length=1, null=True, verbose_name='GENDER')),
                ('rel_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='REL NAME')),
                ('relation', models.CharField(blank=True, max_length=255, null=True, verbose_name='RELATION')),
                ('voter_status', models.CharField(blank=True, max_length=50, null=True, verbose_name='VOTER STATUS')),
                ('party', models.CharField(blank=True, max_length=100, null=True, verbose_name='PARTY')),
                ('caste', models.CharField(blank=True, max_length=100, null=True, verbose_name='CASTE')),
                ('category', models.CharField(blank=True, max_length=100, null=True, verbose_name='CATEGORY')),
                ('verify_status', models.CharField(blank=True, max_length=20, null=True, verbose_name='VERIFY STATUS')),
                ('data', models.JSONField(blank=True, default=dict, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Voter',
                'verbose_name_plural': 'Voters',
                'db_table': 'voters_voter',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VoterField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('datetime', 'DateTime'), ('boolean', 'Boolean'), ('email', 'Email'), ('phone', 'Phone'), ('select', 'Select')], default='text', max_length=50)),
                ('is_required', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Voter Field',
                'verbose_name_plural': 'Voter Fields',
                'db_table': 'voters_voterfield',
                'ordering': ['name'],
            },
        ),
    ]
