# Generated by Django 5.2 on 2025-05-26 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voters', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voter',
            name='mlc_constituency',
        ),
        migrations.AddField(
            model_name='voter',
            name='mlc_constituncy',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='MLC CONSTITUNCY'),
        ),
    ]
