# Generated by Django 5.2 on 2025-05-20 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_remove_timestamp_feild'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='created_by',
        ),
    ]
