# Generated by Django 5.1.7 on 2025-05-27 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Invitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("mobile_number", models.CharField(max_length=15)),
                ("mandal", models.CharField(max_length=100)),
                ("address_venue", models.TextField()),
                ("area", models.CharField(max_length=100)),
                ("file_upload", models.FileField(upload_to="invitations/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("phone_number", models.CharField(max_length=15)),
                ("email", models.EmailField(max_length=254)),
                ("address", models.TextField()),
                ("assembly", models.CharField(max_length=100)),
                ("mandal", models.CharField(max_length=100)),
                ("area", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Assignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_gift_handler", models.BooleanField(default=False)),
                (
                    "invitation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="invitations.invitation",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="invitations.person",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="invitation",
            name="persons",
            field=models.ManyToManyField(
                related_name="invitations",
                through="invitations.Assignment",
                to="invitations.person",
            ),
        ),
    ]
