# Generated by Django 5.2 on 2025-05-22 08:12

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passes', '0005_alter_pass_processed_at_alter_pass_processed_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='pass',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the pass request was created'),
        ),
        migrations.AlterField(
            model_name='pass',
            name='email',
            field=models.EmailField(help_text='Email address for communication and pass delivery', max_length=254),
        ),
        migrations.AlterField(
            model_name='pass',
            name='id_proof_number',
            field=models.CharField(help_text='Number of the selected ID proof', max_length=50, verbose_name='ID Proof Number'),
        ),
        migrations.AlterField(
            model_name='pass',
            name='id_proof_type',
            field=models.CharField(choices=[('AADHAR', 'Aadhar Card'), ('VOTER', 'Voter ID'), ('PAN', 'PAN Card'), ('DL', 'Driving License')], help_text='Type of ID proof being submitted', max_length=10, verbose_name='ID Proof Type'),
        ),
        migrations.AlterField(
            model_name='pass',
            name='name',
            field=models.CharField(help_text='Full name of the primary visitor', max_length=100),
        ),
        migrations.AlterField(
            model_name='pass',
            name='num_persons',
            field=models.PositiveIntegerField(help_text='Number of persons visiting', validators=[django.core.validators.MinValueValidator(1, message='Number of persons must be at least 1')]),
        ),
        migrations.AlterField(
            model_name='pass',
            name='phone',
            field=models.CharField(help_text='10-digit mobile number', max_length=15),
        ),
        migrations.AlterField(
            model_name='pass',
            name='processed_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the pass request was processed', null=True),
        ),
        migrations.AlterField(
            model_name='pass',
            name='processed_by',
            field=models.ForeignKey(blank=True, help_text='Admin user who processed the pass request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_passes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pass',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', help_text='Current status of the pass request', max_length=10),
        ),
        migrations.AlterField(
            model_name='pass',
            name='temple',
            field=models.CharField(choices=[('Sri Mahakaaleshwar Mandir', 'Sri Mahakaaleshwar Mandir'), ('Tirumala Tirupati Devasthanam', 'Tirumala Tirupati Devasthanam'), ('Dwaraka Tirumala Devasthanam', 'Dwaraka Tirumala Devasthanam'), ('Sree Padmanabha Swamy Devasthanam', 'Sree Padmanabha Swamy Devasthanam'), ('Sri Bhramaramba Mallikarjuna Swamy Varla Devasthanam', 'Sri Bhramaramba Mallikarjuna Swamy Varla Devasthanam'), ('Sri Gnanaprasunambika Sametha Srikalahasteeswara Temple', 'Sri Gnanaprasunambika Sametha Srikalahasteeswara Temple'), ('Shri Shirdi Sayee Samsthan', 'Shri Shirdi Sayee Samsthan'), ('Sabarimala Sree Ayyappa Devasthanam', 'Sabarimala Sree Ayyappa Devasthanam'), ('Shree Jagannath Temple', 'Shree Jagannath Temple'), ('Shri Kashi Vishwanath Temple', 'Shri Kashi Vishwanath Temple'), ('Swayambhu Sri Varasiddhi Vinayaka Swamy', 'Swayambhu Sri Varasiddhi Vinayaka Swamy'), ('Sri Kamakshi Ambal Devasthanam', 'Sri Kamakshi Ambal Devasthanam'), ('Ram Lala Ayodha', 'Ram Lala Ayodha'), ('Arulmigu Arunachaleswarar Temple', 'Arulmigu Arunachaleswarar Temple')], help_text='Select the temple you wish to visit', max_length=100),
        ),
        migrations.AlterField(
            model_name='pass',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the pass request was last updated'),
        ),
        migrations.AlterField(
            model_name='pass',
            name='visit_date',
            field=models.DateField(help_text='Planned date of visit'),
        ),
        migrations.AddIndex(
            model_name='pass',
            index=models.Index(fields=['temple', 'visit_date', 'status'], name='passes_pass_temple_d21b1d_idx'),
        ),
        migrations.AddIndex(
            model_name='pass',
            index=models.Index(fields=['status', 'created_at'], name='passes_pass_status_55a107_idx'),
        ),
    ]
