# Generated by Django 5.1.7 on 2025-05-26 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("passes", "0006_alter_pass_created_at_alter_pass_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pass",
            name="accommodation_date",
            field=models.DateField(
                blank=True, help_text="Accommodation date (if applicable)", null=True
            ),
        ),
        migrations.AddField(
            model_name="pass",
            name="darshan_date",
            field=models.DateField(
                blank=True, help_text="Darshan date (if applicable)", null=True
            ),
        ),
        migrations.AddField(
            model_name="pass",
            name="darshan_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("REGULAR", "Regular"),
                    ("SPECIAL", "Special"),
                    ("VVIP", "VVIP"),
                    ("SPARSHA", "Sparsha"),
                ],
                help_text="Type of darshan (admin can set this)",
                max_length=20,
                null=True,
            ),
        ),
    ]
